### ISSUE TITLE
Can you create example where you add moments js library to this angular app

### ISSUE THREAD

**Issue by kashcode** [FabianGosebrink/ASPNETCore-Angular-SystemJS-StarterTemplate#10]

**Comment by FabianGosebrink** [comment]
Well you only have to do an `npm install ...` from momentjs and then `import * as moment from 'moment';` :-) Does that work for you?

**Comment by kashcode** [comment]
Actually no, I get error:
```
ERROR Error: Uncaught (in promise): TypeError: moment is not a function
```
[system.config.js](https://github.com/kashcode/ASPNETCore-Angular-SystemJS-StarterTemplate/blob/master/src/ASPNETCoreAngular2Demo/system.config.js)

In home component I try output in console moment()
```

ngOnInit() {
--
  | console.log(moment());

```
[home.component.ts](https://github.com/kashcode/ASPNETCore-Angular-SystemJS-StarterTemplate/blob/master/src/ASPNETCoreAngular2Demo/angularApp/home/components/home/home.component.ts)

**Comment by FabianGosebrink** [comment]
Please do it like this:

```
(function (global) {
  System.config({
    ...
    // map tells the System loader where to look for things
    map: {
      ...
      'moment': 'npm:moment-with-locales.js',
      ...
    },
    // packages tells the System loader how to load when no filename and/or no extension
    packages: {
      ....
      'moment': {
          defaultExtension: 'js'
      }
    }
  });
})(this);
```

**Comment by kashcode** [comment]
That's fix the problem. Thanks.

P.S.
But I don't understand how :-(
